Vagrant.configure("2") do |config|
config.vm.hostname = 'vagrant-test'

if ENV['ENV'] != 'local' 
  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.nfs.functional = false
    override.vm.allowed_synced_folder_types = :rsync

    provider.token = ''  # Remember to remove before committing! Use an environment variable instead.
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = '512mb'
    provider.setup = false
end
end

config.puppet_install.puppet_version = :latest 
config.vm.provision :puppet

config.vm.define "dbserver" do |db|
    db.vm.box = "bento/ubuntu-18.04"
    db.vm.hostname = "dbserver.node"
  end
  
config.vm.define "appserver" do |app|
    app.vm.box = "bento/ubuntu-18.04"
    app.vm.hostname = "appserver.node"
  end

end
